# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selfcheckout.ui'
#
# Created: Fri Mar 03 01:16:14 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from subprocess import call

class MyLineEdit(QtGui.QLineEdit):
    def __init__(self, parent=None):
        super(MyLineEdit, self).__init__(parent)

    def focusInEvent(self, e):
        call(["onboard"])


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setMaximumSize(QtCore.QSize(1366, 768))
        MainWindow.setBaseSize(QtCore.QSize(1366, 768))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 768))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 745))
        self.stackedWidget.setObjectName("stackedWidget")
        self.startPage = QtGui.QWidget()
        self.startPage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startPage.setObjectName("startPage")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.startPage)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.startPage)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(645, 500))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(645, 500))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/QR-code-ATA_transparent.png"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.startButton = QtGui.QPushButton(self.startPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(300, 100))
        self.startButton.setBaseSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.startButton.setFont(font)
        self.startButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.startPage)
        self.workPage = QtGui.QWidget()
        self.workPage.setObjectName("workPage")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.workPage)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget_3 = QtGui.QStackedWidget(self.workPage)
        self.stackedWidget_3.setMinimumSize(QtCore.QSize(975, 725))
        self.stackedWidget_3.setMaximumSize(QtCore.QSize(975, 725))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page = QtGui.QWidget()
        self.page.setMinimumSize(QtCore.QSize(67, 0))
        self.page.setObjectName("page")
        self.widget = QtGui.QWidget(self.page)
        self.widget.setGeometry(QtCore.QRect(0, 0, 973, 725))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mapGroupBox = QtGui.QGroupBox(self.widget)
        self.mapGroupBox.setMinimumSize(QtCore.QSize(0, 355))
        self.mapGroupBox.setTitle("")
        self.mapGroupBox.setObjectName("mapGroupBox")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.mapGroupBox)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mapGraphicsView = QtGui.QLabel(self.mapGroupBox)
        self.mapGraphicsView.setMinimumSize(QtCore.QSize(951, 314))
        self.mapGraphicsView.setMaximumSize(QtCore.QSize(951, 314))
        self.mapGraphicsView.setText("")
        self.mapGraphicsView.setPixmap(QtGui.QPixmap("images/Plan Superm_1.00_00_00_00.Still001.png").scaled(self.mapGraphicsView.width(), self.mapGraphicsView.height(),
                                                                                                             QtCore.Qt.KeepAspectRatio))
        self.mapGraphicsView.setScaledContents(False)
        self.mapGraphicsView.setAlignment(QtCore.Qt.AlignCenter)
        self.mapGraphicsView.setObjectName("mapGraphicsView")
        self.horizontalLayout_8.addWidget(self.mapGraphicsView)
        self.verticalLayout_4.addWidget(self.mapGroupBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.productInfoGroupBox = QtGui.QGroupBox(self.widget)
        self.productInfoGroupBox.setMinimumSize(QtCore.QSize(455, 0))
        self.productInfoGroupBox.setMaximumSize(QtCore.QSize(455, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.productInfoGroupBox.setFont(font)
        self.productInfoGroupBox.setObjectName("productInfoGroupBox")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.productInfoGroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.nameGoodLabel = QtGui.QLabel(self.productInfoGroupBox)
        self.nameGoodLabel.setObjectName("nameGoodLabel")
        self.verticalLayout_7.addWidget(self.nameGoodLabel)
        self.line_2 = QtGui.QFrame(self.productInfoGroupBox)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.descriptionGoodLabel = QtGui.QLabel(self.productInfoGroupBox)
        self.descriptionGoodLabel.setWordWrap(True)
        self.descriptionGoodLabel.setObjectName("descriptionGoodLabel")
        self.verticalLayout_7.addWidget(self.descriptionGoodLabel)
        self.line_3 = QtGui.QFrame(self.productInfoGroupBox)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_7.addWidget(self.line_3)
        self.expirationGoodLabel = QtGui.QLabel(self.productInfoGroupBox)
        self.expirationGoodLabel.setObjectName("expirationGoodLabel")
        self.verticalLayout_7.addWidget(self.expirationGoodLabel)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.imageGoodLabel = QtGui.QLabel(self.productInfoGroupBox)
        self.imageGoodLabel.setMinimumSize(QtCore.QSize(211, 247))
        self.imageGoodLabel.setMaximumSize(QtCore.QSize(211, 247))
        self.imageGoodLabel.setText("")
        self.imageGoodLabel.setScaledContents(False)
        self.imageGoodLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageGoodLabel.setObjectName("imageGoodLabel")
        self.horizontalLayout_6.addWidget(self.imageGoodLabel)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.addFavPushButton = QtGui.QPushButton(self.productInfoGroupBox)
        self.addFavPushButton.setMinimumSize(QtCore.QSize(140, 58))
        self.addFavPushButton.setMaximumSize(QtCore.QSize(140, 58))
        self.addFavPushButton.setObjectName("addFavPushButton")
        self.horizontalLayout_14.addWidget(self.addFavPushButton)
        self.delCartPushButton = QtGui.QPushButton(self.productInfoGroupBox)
        self.delCartPushButton.setMinimumSize(QtCore.QSize(140, 58))
        self.delCartPushButton.setMaximumSize(QtCore.QSize(140, 58))
        self.delCartPushButton.setObjectName("delCartPushButton")
        self.horizontalLayout_14.addWidget(self.delCartPushButton)
        self.goToPushButton = QtGui.QPushButton(self.productInfoGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goToPushButton.sizePolicy().hasHeightForWidth())
        self.goToPushButton.setSizePolicy(sizePolicy)
        self.goToPushButton.setMinimumSize(QtCore.QSize(140, 58))
        self.goToPushButton.setMaximumSize(QtCore.QSize(140, 58))
        self.goToPushButton.setObjectName("goToPushButton")
        self.horizontalLayout_14.addWidget(self.goToPushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_3.addWidget(self.productInfoGroupBox)
        self.stackedWidget_2 = QtGui.QStackedWidget(self.widget)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.discountPage = QtGui.QWidget()
        self.discountPage.setObjectName("discountPage")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.discountPage)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.discountGroupBox = QtGui.QGroupBox(self.discountPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.discountGroupBox.setFont(font)
        self.discountGroupBox.setObjectName("discountGroupBox")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.discountGroupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame = QtGui.QFrame(self.discountGroupBox)
        self.frame.setMinimumSize(QtCore.QSize(152, 90))
        self.frame.setMaximumSize(QtCore.QSize(152, 90))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.discountImageLabel1 = QtGui.QLabel(self.frame)
        self.discountImageLabel1.setGeometry(QtCore.QRect(30, 20, 81, 51))
        self.discountImageLabel1.setText("")
        self.discountImageLabel1.setPixmap(QtGui.QPixmap("images/991.jpg"))
        self.discountImageLabel1.setScaledContents(False)
        self.discountImageLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.discountImageLabel1.setObjectName("discountImageLabel1")
        self.discountPriceLabel1 = QtGui.QLabel(self.frame)
        self.discountPriceLabel1.setGeometry(QtCore.QRect(90, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountPriceLabel1.setFont(font)
        self.discountPriceLabel1.setObjectName("discountPriceLabel1")
        self.discountNameLabel1 = QtGui.QLabel(self.frame)
        self.discountNameLabel1.setGeometry(QtCore.QRect(5, 5, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountNameLabel1.setFont(font)
        self.discountNameLabel1.setObjectName("discountNameLabel1")
        self.discountPushButton1 = QtGui.QPushButton(self.frame)
        self.discountPushButton1.setGeometry(QtCore.QRect(0, 0, 155, 90))
        self.discountPushButton1.setText("")
        self.discountPushButton1.setFlat(True)
        self.discountPushButton1.setObjectName("discountPushButton1")
        self.horizontalLayout_12.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.discountGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(152, 90))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.discountNameLabel2 = QtGui.QLabel(self.frame_2)
        self.discountNameLabel2.setGeometry(QtCore.QRect(5, 5, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountNameLabel2.setFont(font)
        self.discountNameLabel2.setObjectName("discountNameLabel2")
        self.discountImageLabel2 = QtGui.QLabel(self.frame_2)
        self.discountImageLabel2.setGeometry(QtCore.QRect(30, 20, 81, 51))
        self.discountImageLabel2.setText("")
        self.discountImageLabel2.setPixmap(QtGui.QPixmap("images/9402-bananas.jpg"))
        self.discountImageLabel2.setScaledContents(False)
        self.discountImageLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.discountImageLabel2.setObjectName("discountImageLabel2")
        self.discountPriceLabel2 = QtGui.QLabel(self.frame_2)
        self.discountPriceLabel2.setGeometry(QtCore.QRect(90, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountPriceLabel2.setFont(font)
        self.discountPriceLabel2.setObjectName("discountPriceLabel2")
        self.discountPushButton2 = QtGui.QPushButton(self.frame_2)
        self.discountPushButton2.setGeometry(QtCore.QRect(0, 0, 155, 90))
        self.discountPushButton2.setText("")
        self.discountPushButton2.setFlat(True)
        self.discountPushButton2.setObjectName("discountPushButton2")
        self.horizontalLayout_12.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.discountGroupBox)
        self.frame_3.setMinimumSize(QtCore.QSize(152, 90))
        self.frame_3.setMaximumSize(QtCore.QSize(152, 90))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.discountNameLabel3 = QtGui.QLabel(self.frame_3)
        self.discountNameLabel3.setGeometry(QtCore.QRect(5, 5, 59, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountNameLabel3.setFont(font)
        self.discountNameLabel3.setFrameShape(QtGui.QFrame.NoFrame)
        self.discountNameLabel3.setObjectName("discountNameLabel3")
        self.discountImageLabel3 = QtGui.QLabel(self.frame_3)
        self.discountImageLabel3.setGeometry(QtCore.QRect(30, 20, 81, 51))
        self.discountImageLabel3.setText("")
        self.discountImageLabel3.setPixmap(QtGui.QPixmap("images/salami.jpg"))
        self.discountImageLabel3.setScaledContents(False)
        self.discountImageLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.discountImageLabel3.setObjectName("discountImageLabel3")
        self.discountPriceLabel3 = QtGui.QLabel(self.frame_3)
        self.discountPriceLabel3.setGeometry(QtCore.QRect(80, 70, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountPriceLabel3.setFont(font)
        self.discountPriceLabel3.setObjectName("discountPriceLabel3")
        self.discountPushButton3 = QtGui.QPushButton(self.frame_3)
        self.discountPushButton3.setGeometry(QtCore.QRect(0, 0, 155, 90))
        self.discountPushButton3.setText("")
        self.discountPushButton3.setFlat(True)
        self.discountPushButton3.setObjectName("discountPushButton3")
        self.horizontalLayout_12.addWidget(self.frame_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_4 = QtGui.QFrame(self.discountGroupBox)
        self.frame_4.setMinimumSize(QtCore.QSize(152, 90))
        self.frame_4.setMaximumSize(QtCore.QSize(152, 90))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.discountImageLabel4 = QtGui.QLabel(self.frame_4)
        self.discountImageLabel4.setGeometry(QtCore.QRect(30, 20, 81, 51))
        self.discountImageLabel4.setText("")
        self.discountImageLabel4.setPixmap(QtGui.QPixmap("images/FrenchBaguette.jpg"))
        self.discountImageLabel4.setScaledContents(False)
        self.discountImageLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.discountImageLabel4.setObjectName("discountImageLabel4")
        self.discountPriceLabel4 = QtGui.QLabel(self.frame_4)
        self.discountPriceLabel4.setGeometry(QtCore.QRect(90, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountPriceLabel4.setFont(font)
        self.discountPriceLabel4.setObjectName("discountPriceLabel4")
        self.discountNameLabel4 = QtGui.QLabel(self.frame_4)
        self.discountNameLabel4.setGeometry(QtCore.QRect(5, 5, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountNameLabel4.setFont(font)
        self.discountNameLabel4.setObjectName("discountNameLabel4")
        self.discountPushButton4 = QtGui.QPushButton(self.frame_4)
        self.discountPushButton4.setGeometry(QtCore.QRect(0, 0, 155, 90))
        self.discountPushButton4.setText("")
        self.discountPushButton4.setFlat(True)
        self.discountPushButton4.setObjectName("discountPushButton4")
        self.horizontalLayout_10.addWidget(self.frame_4)
        self.frame_6 = QtGui.QFrame(self.discountGroupBox)
        self.frame_6.setMinimumSize(QtCore.QSize(152, 90))
        self.frame_6.setMaximumSize(QtCore.QSize(152, 90))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.discountImageLabel5 = QtGui.QLabel(self.frame_6)
        self.discountImageLabel5.setGeometry(QtCore.QRect(30, 20, 81, 51))
        self.discountImageLabel5.setText("")
        self.discountImageLabel5.setPixmap(QtGui.QPixmap("images/img-fiche-silver-sardine-huile-vegetale.png"))
        self.discountImageLabel5.setScaledContents(False)
        self.discountImageLabel5.setAlignment(QtCore.Qt.AlignCenter)
        self.discountImageLabel5.setObjectName("discountImageLabel5")
        self.discountPriceLabel5 = QtGui.QLabel(self.frame_6)
        self.discountPriceLabel5.setGeometry(QtCore.QRect(90, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountPriceLabel5.setFont(font)
        self.discountPriceLabel5.setObjectName("discountPriceLabel5")
        self.discountNameLabel5 = QtGui.QLabel(self.frame_6)
        self.discountNameLabel5.setGeometry(QtCore.QRect(5, 5, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountNameLabel5.setFont(font)
        self.discountNameLabel5.setObjectName("discountNameLabel5")
        self.discountPushButton5 = QtGui.QPushButton(self.frame_6)
        self.discountPushButton5.setGeometry(QtCore.QRect(0, 0, 155, 90))
        self.discountPushButton5.setText("")
        self.discountPushButton5.setFlat(True)
        self.discountPushButton5.setObjectName("discountPushButton5")
        self.horizontalLayout_10.addWidget(self.frame_6)
        self.frame_5 = QtGui.QFrame(self.discountGroupBox)
        self.frame_5.setMinimumSize(QtCore.QSize(152, 90))
        self.frame_5.setMaximumSize(QtCore.QSize(152, 90))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.discountImageLabel6 = QtGui.QLabel(self.frame_5)
        self.discountImageLabel6.setGeometry(QtCore.QRect(30, 20, 81, 51))
        self.discountImageLabel6.setText("")
        self.discountImageLabel6.setPixmap(QtGui.QPixmap("images/Lemon_easter_biscuits_hero_1d74c01d.jpg"))
        self.discountImageLabel6.setScaledContents(False)
        self.discountImageLabel6.setAlignment(QtCore.Qt.AlignCenter)
        self.discountImageLabel6.setObjectName("discountImageLabel6")
        self.discountPriceLabel6 = QtGui.QLabel(self.frame_5)
        self.discountPriceLabel6.setGeometry(QtCore.QRect(90, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountPriceLabel6.setFont(font)
        self.discountPriceLabel6.setObjectName("discountPriceLabel6")
        self.discountNameLabel6 = QtGui.QLabel(self.frame_5)
        self.discountNameLabel6.setGeometry(QtCore.QRect(5, 5, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountNameLabel6.setFont(font)
        self.discountNameLabel6.setObjectName("discountNameLabel6")
        self.discountPushButton6 = QtGui.QPushButton(self.frame_5)
        self.discountPushButton6.setGeometry(QtCore.QRect(0, 0, 155, 90))
        self.discountPushButton6.setText("")
        self.discountPushButton6.setFlat(True)
        self.discountPushButton6.setObjectName("discountPushButton6")
        self.horizontalLayout_10.addWidget(self.frame_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_7 = QtGui.QFrame(self.discountGroupBox)
        self.frame_7.setMinimumSize(QtCore.QSize(152, 90))
        self.frame_7.setMaximumSize(QtCore.QSize(152, 90))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.discountImageLabel7 = QtGui.QLabel(self.frame_7)
        self.discountImageLabel7.setGeometry(QtCore.QRect(40, 20, 81, 51))
        self.discountImageLabel7.setText("")
        self.discountImageLabel7.setPixmap(QtGui.QPixmap("images/liquor-bottle-IARzFh-clipart.jpg"))
        self.discountImageLabel7.setScaledContents(False)
        self.discountImageLabel7.setAlignment(QtCore.Qt.AlignCenter)
        self.discountImageLabel7.setObjectName("discountImageLabel7")
        self.discountPriceLabel7 = QtGui.QLabel(self.frame_7)
        self.discountPriceLabel7.setGeometry(QtCore.QRect(80, 70, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountPriceLabel7.setFont(font)
        self.discountPriceLabel7.setObjectName("discountPriceLabel7")
        self.discountNameLabel7 = QtGui.QLabel(self.frame_7)
        self.discountNameLabel7.setGeometry(QtCore.QRect(5, 5, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountNameLabel7.setFont(font)
        self.discountNameLabel7.setObjectName("discountNameLabel7")
        self.discountPushButton7 = QtGui.QPushButton(self.frame_7)
        self.discountPushButton7.setGeometry(QtCore.QRect(0, 0, 155, 90))
        self.discountPushButton7.setText("")
        self.discountPushButton7.setFlat(True)
        self.discountPushButton7.setObjectName("discountPushButton7")
        self.horizontalLayout_13.addWidget(self.frame_7)
        self.frame_9 = QtGui.QFrame(self.discountGroupBox)
        self.frame_9.setMinimumSize(QtCore.QSize(152, 90))
        self.frame_9.setMaximumSize(QtCore.QSize(152, 90))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.discountImageLabel8 = QtGui.QLabel(self.frame_9)
        self.discountImageLabel8.setGeometry(QtCore.QRect(30, 20, 81, 51))
        self.discountImageLabel8.setText("")
        self.discountImageLabel8.setPixmap(QtGui.QPixmap("images/marinated-tomatoes-with-garlic.jpg"))
        self.discountImageLabel8.setScaledContents(False)
        self.discountImageLabel8.setAlignment(QtCore.Qt.AlignCenter)
        self.discountImageLabel8.setObjectName("discountImageLabel8")
        self.discountPriceLabel8 = QtGui.QLabel(self.frame_9)
        self.discountPriceLabel8.setGeometry(QtCore.QRect(90, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountPriceLabel8.setFont(font)
        self.discountPriceLabel8.setObjectName("discountPriceLabel8")
        self.discountNameLabel8 = QtGui.QLabel(self.frame_9)
        self.discountNameLabel8.setGeometry(QtCore.QRect(5, 5, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountNameLabel8.setFont(font)
        self.discountNameLabel8.setObjectName("discountNameLabel8")
        self.discountPushButton8 = QtGui.QPushButton(self.frame_9)
        self.discountPushButton8.setGeometry(QtCore.QRect(0, 0, 155, 90))
        self.discountPushButton8.setText("")
        self.discountPushButton8.setFlat(True)
        self.discountPushButton8.setObjectName("discountPushButton8")
        self.horizontalLayout_13.addWidget(self.frame_9)
        self.frame_8 = QtGui.QFrame(self.discountGroupBox)
        self.frame_8.setMinimumSize(QtCore.QSize(152, 90))
        self.frame_8.setMaximumSize(QtCore.QSize(152, 90))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.discountImageLabel9 = QtGui.QLabel(self.frame_8)
        self.discountImageLabel9.setGeometry(QtCore.QRect(30, 20, 81, 51))
        self.discountImageLabel9.setText("")
        self.discountImageLabel9.setPixmap(QtGui.QPixmap("images/Swiss_Cheese_Garden_of_Eden_jpg.jpg"))
        self.discountImageLabel9.setScaledContents(False)
        self.discountImageLabel9.setAlignment(QtCore.Qt.AlignCenter)
        self.discountImageLabel9.setObjectName("discountImageLabel9")
        self.discountPriceLabel9 = QtGui.QLabel(self.frame_8)
        self.discountPriceLabel9.setGeometry(QtCore.QRect(80, 70, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountPriceLabel9.setFont(font)
        self.discountPriceLabel9.setObjectName("discountPriceLabel9")
        self.discountNameLabel9 = QtGui.QLabel(self.frame_8)
        self.discountNameLabel9.setGeometry(QtCore.QRect(5, 5, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.discountNameLabel9.setFont(font)
        self.discountNameLabel9.setObjectName("discountNameLabel9")
        self.discountPushButton9 = QtGui.QPushButton(self.frame_8)
        self.discountPushButton9.setGeometry(QtCore.QRect(0, 0, 155, 90))
        self.discountPushButton9.setText("")
        self.discountPushButton9.setFlat(True)
        self.discountPushButton9.setObjectName("discountPushButton9")
        self.horizontalLayout_13.addWidget(self.frame_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_11.addWidget(self.discountGroupBox)
        self.stackedWidget_2.addWidget(self.discountPage)
        self.findProductPage = QtGui.QWidget()
        self.findProductPage.setObjectName("findProductPage")
        self.verticalLayout = QtGui.QVBoxLayout(self.findProductPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.findProductGroupBox = QtGui.QGroupBox(self.findProductPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.findProductGroupBox.setFont(font)
        self.findProductGroupBox.setObjectName("findProductGroupBox")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.findProductGroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.findLineEdit = MyLineEdit(self.findProductGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.findLineEdit.setFont(font)
        self.findLineEdit.setObjectName("findLineEdit")
        self.verticalLayout_6.addWidget(self.findLineEdit)
        self.foundedListWidget = QtGui.QListWidget(self.findProductGroupBox)
        self.foundedListWidget.setObjectName("foundedListWidget")
        self.verticalLayout_6.addWidget(self.foundedListWidget)
        self.verticalLayout.addWidget(self.findProductGroupBox)
        self.stackedWidget_2.addWidget(self.findProductPage)
        self.horizontalLayout_3.addWidget(self.stackedWidget_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.stackedWidget_3.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_10 = QtGui.QFrame(self.page_2)
        self.frame_10.setGeometry(QtCore.QRect(-1, -1, 981, 721))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.widget1 = QtGui.QWidget(self.frame_10)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 981, 721))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtGui.QLabel(self.widget1)
        self.label_3.setMinimumSize(QtCore.QSize(0, 10))
        self.label_3.setMaximumSize(QtCore.QSize(16777208, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.line_4 = QtGui.QFrame(self.widget1)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.label_4 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.line_5 = QtGui.QFrame(self.widget1)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_5.addWidget(self.line_5)
        self.label_5 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.proceedPushButton = QtGui.QPushButton(self.page_2)
        self.proceedPushButton.setGeometry(QtCore.QRect(0, 0, 981, 723))
        self.proceedPushButton.setText("")
        self.proceedPushButton.setFlat(True)
        self.proceedPushButton.setObjectName("proceedPushButton")
        self.stackedWidget_3.addWidget(self.page_2)
        self.horizontalLayout_5.addWidget(self.stackedWidget_3)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.shopingCartLabel = QtGui.QLabel(self.workPage)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.shopingCartLabel.setFont(font)
        self.shopingCartLabel.setLineWidth(1)
        self.shopingCartLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.shopingCartLabel.setObjectName("shopingCartLabel")
        self.verticalLayout_3.addWidget(self.shopingCartLabel)
        self.barcodeLineEdit = MyLineEdit(self.workPage)
        self.barcodeLineEdit.setProperty("clearButtonEnabled", False)
        self.barcodeLineEdit.setObjectName("barcodeLineEdit")
        self.verticalLayout_3.addWidget(self.barcodeLineEdit)
        self.shopingCartListWidget = QtGui.QListWidget(self.workPage)
        self.shopingCartListWidget.setObjectName("shopingCartListWidget")
        self.verticalLayout_3.addWidget(self.shopingCartListWidget)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.shopingCartTotalLabel = QtGui.QLabel(self.workPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shopingCartTotalLabel.setFont(font)
        self.shopingCartTotalLabel.setObjectName("shopingCartTotalLabel")
        self.horizontalLayout_9.addWidget(self.shopingCartTotalLabel)
        self.shopingCartTotalSumLabel = QtGui.QLabel(self.workPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shopingCartTotalSumLabel.setFont(font)
        self.shopingCartTotalSumLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shopingCartTotalSumLabel.setObjectName("shopingCartTotalSumLabel")
        self.horizontalLayout_9.addWidget(self.shopingCartTotalSumLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.findPushButton = QtGui.QPushButton(self.workPage)
        self.findPushButton.setMinimumSize(QtCore.QSize(64, 64))
        self.findPushButton.setMaximumSize(QtCore.QSize(64, 64))
        self.findPushButton.setBaseSize(QtCore.QSize(64, 64))
        self.findPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico/ic_search_black_48dp_1x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findPushButton.setIcon(icon)
        self.findPushButton.setIconSize(QtCore.QSize(64, 64))
        self.findPushButton.setObjectName("findPushButton")
        self.horizontalLayout_2.addWidget(self.findPushButton)
        self.mapPushButton = QtGui.QPushButton(self.workPage)
        self.mapPushButton.setMinimumSize(QtCore.QSize(64, 64))
        self.mapPushButton.setMaximumSize(QtCore.QSize(64, 64))
        self.mapPushButton.setBaseSize(QtCore.QSize(64, 64))
        self.mapPushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ico/ic_room_black_48dp_1x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mapPushButton.setIcon(icon1)
        self.mapPushButton.setIconSize(QtCore.QSize(64, 64))
        self.mapPushButton.setObjectName("mapPushButton")
        self.horizontalLayout_2.addWidget(self.mapPushButton)
        self.delPushButton = QtGui.QPushButton(self.workPage)
        self.delPushButton.setMinimumSize(QtCore.QSize(64, 64))
        self.delPushButton.setMaximumSize(QtCore.QSize(64, 64))
        self.delPushButton.setBaseSize(QtCore.QSize(64, 64))
        self.delPushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ico/ic_highlight_off_black_48dp_1x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delPushButton.setIcon(icon2)
        self.delPushButton.setIconSize(QtCore.QSize(64, 64))
        self.delPushButton.setObjectName("delPushButton")
        self.horizontalLayout_2.addWidget(self.delPushButton)
        self.favoritesPushButton = QtGui.QPushButton(self.workPage)
        self.favoritesPushButton.setMinimumSize(QtCore.QSize(64, 64))
        self.favoritesPushButton.setMaximumSize(QtCore.QSize(64, 64))
        self.favoritesPushButton.setBaseSize(QtCore.QSize(64, 64))
        self.favoritesPushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ico/ic_grade_black_48dp_1x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.favoritesPushButton.setIcon(icon3)
        self.favoritesPushButton.setIconSize(QtCore.QSize(64, 64))
        self.favoritesPushButton.setObjectName("favoritesPushButton")
        self.horizontalLayout_2.addWidget(self.favoritesPushButton)
        self.cartPushButton = QtGui.QPushButton(self.workPage)
        self.cartPushButton.setMinimumSize(QtCore.QSize(64, 64))
        self.cartPushButton.setMaximumSize(QtCore.QSize(64, 64))
        self.cartPushButton.setBaseSize(QtCore.QSize(64, 64))
        self.cartPushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ico/shopping-cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cartPushButton.setIcon(icon4)
        self.cartPushButton.setIconSize(QtCore.QSize(48, 48))
        self.cartPushButton.setObjectName("cartPushButton")
        self.horizontalLayout_2.addWidget(self.cartPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.workPage)
        self.verticalLayout_11.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_3.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Brand Logo", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start Shopping without Login", None, QtGui.QApplication.UnicodeUTF8))
        self.productInfoGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Product information", None, QtGui.QApplication.UnicodeUTF8))
        self.nameGoodLabel.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptionGoodLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.expirationGoodLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.addFavPushButton.setText(QtGui.QApplication.translate("MainWindow", "Add to \n"
"Favorites", None, QtGui.QApplication.UnicodeUTF8))
        self.delCartPushButton.setText(QtGui.QApplication.translate("MainWindow", "Delete \n"
"From Cart", None, QtGui.QApplication.UnicodeUTF8))
        self.goToPushButton.setText(QtGui.QApplication.translate("MainWindow", "Go to", None, QtGui.QApplication.UnicodeUTF8))
        self.discountGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Discounts Today", None, QtGui.QApplication.UnicodeUTF8))
        self.discountPriceLabel1.setText(QtGui.QApplication.translate("MainWindow", "1.29€", None, QtGui.QApplication.UnicodeUTF8))
        self.discountNameLabel1.setText(QtGui.QApplication.translate("MainWindow", "Bread", None, QtGui.QApplication.UnicodeUTF8))
        self.discountNameLabel2.setText(QtGui.QApplication.translate("MainWindow", "Banana", None, QtGui.QApplication.UnicodeUTF8))
        self.discountPriceLabel2.setText(QtGui.QApplication.translate("MainWindow", "2.19€", None, QtGui.QApplication.UnicodeUTF8))
        self.discountNameLabel3.setText(QtGui.QApplication.translate("MainWindow", "Salami", None, QtGui.QApplication.UnicodeUTF8))
        self.discountPriceLabel3.setText(QtGui.QApplication.translate("MainWindow", "10.69€", None, QtGui.QApplication.UnicodeUTF8))
        self.discountPriceLabel4.setText(QtGui.QApplication.translate("MainWindow", "1.29€", None, QtGui.QApplication.UnicodeUTF8))
        self.discountNameLabel4.setText(QtGui.QApplication.translate("MainWindow", "French bread", None, QtGui.QApplication.UnicodeUTF8))
        self.discountPriceLabel5.setText(QtGui.QApplication.translate("MainWindow", "3.79€", None, QtGui.QApplication.UnicodeUTF8))
        self.discountNameLabel5.setText(QtGui.QApplication.translate("MainWindow", "Fish conserve", None, QtGui.QApplication.UnicodeUTF8))
        self.discountPriceLabel6.setText(QtGui.QApplication.translate("MainWindow", "2.89€", None, QtGui.QApplication.UnicodeUTF8))
        self.discountNameLabel6.setText(QtGui.QApplication.translate("MainWindow", "Lemon", None, QtGui.QApplication.UnicodeUTF8))
        self.discountPriceLabel7.setText(QtGui.QApplication.translate("MainWindow", "27.99€", None, QtGui.QApplication.UnicodeUTF8))
        self.discountNameLabel7.setText(QtGui.QApplication.translate("MainWindow", "Alcohol", None, QtGui.QApplication.UnicodeUTF8))
        self.discountPriceLabel8.setText(QtGui.QApplication.translate("MainWindow", "8.99€", None, QtGui.QApplication.UnicodeUTF8))
        self.discountNameLabel8.setText(QtGui.QApplication.translate("MainWindow", "Tomatoes", None, QtGui.QApplication.UnicodeUTF8))
        self.discountPriceLabel9.setText(QtGui.QApplication.translate("MainWindow", "19.99€", None, QtGui.QApplication.UnicodeUTF8))
        self.discountNameLabel9.setText(QtGui.QApplication.translate("MainWindow", "Cheese", None, QtGui.QApplication.UnicodeUTF8))
        self.findProductGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Find Product", None, QtGui.QApplication.UnicodeUTF8))
        self.findLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Enter Product Name Here...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Thanks for Shopping\n"
"Peter Peterechuk!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Proceed Payment with \n"
"Your Credit Card", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Have a nice day!", None, QtGui.QApplication.UnicodeUTF8))
        self.shopingCartLabel.setText(QtGui.QApplication.translate("MainWindow", "Shopping cart", None, QtGui.QApplication.UnicodeUTF8))
        self.barcodeLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Insert barcode here..", None, QtGui.QApplication.UnicodeUTF8))
        self.shopingCartTotalLabel.setText(QtGui.QApplication.translate("MainWindow", "TOTAL", None, QtGui.QApplication.UnicodeUTF8))
        self.shopingCartTotalSumLabel.setText(QtGui.QApplication.translate("MainWindow", "0,00", None, QtGui.QApplication.UnicodeUTF8))

